; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano-bluetoothControlledCar]
platform = atmelavr
board = nanoatmega328
framework = arduino
src_dir = src/bluetoothControlledCar

[env:nano-bluetoothLEDs]
platform = atmelavr
board = nanoatmega328
framework = arduino
src_dir = src/bluetoothLEDs

[env:nano-bluetoothEnvironment]
platform = atmelavr
board = nanoatmega328
framework = arduino
src_dir = src/bluetoothEnvironment

[env:nano-simpleLEDs]
platform = atmelavr
board = nanoatmega328
framework = arduino
src_dir = src/simpleLEDs

[env:nano-simpleTrafficSignal]
platform = atmelavr
board = nanoatmega328
framework = arduino
src_dir = src/simpleTrafficSignal
